Search for rst2html.py if rst2html isn't found
Also die during make if rst2html is needed but not found.

Reviewed-by: imsnah


git-svn-id: http://neatx.googlecode.com/svn/trunk@58 b50b1b54-5739-11de-8832-3f4c773c73ae

diff --git a/neatx/Makefile.am b/neatx/Makefile.am
--- a/neatx/Makefile.am
+++ b/neatx/Makefile.am
@@ -146,7 +146,8 @@ $(TESTS): neatx srclinks lib/_autoconf.py src/fdcopy src/ttysetup
 
 doc/%.html: doc/%.rst
 	@if test -z "$(RST2HTML)"; then \
-		echo 'rst2html not found during configure, not building docs'; \
+		echo "rst2html not found during configure, can't build docs"; \
+		exit 1; \
 	else \
 		$(RST2HTML) $< $@; \
 	fi
